[package]
name = "querynot"
description = "A local-first desktop SQL client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "querynot_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
base64.workspace = true
querynot-core = { path = "../crates/querynot-core", version = "0.0.0" }
secrecy.workspace = true
serde.workspace = true
sqlformat.workspace = true
tauri = { version = "2.11.5", features = [] }
tauri-plugin-dialog = "2.7.2"
tauri-plugin-single-instance = "2.4.3"
tokio.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile = "3.23.0"
