import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const schemaPath = resolve(root, 'contracts/querynot.v1.json');
const rustPath = resolve(
  root,
  'crates/querynot-core/src/generated/contracts.rs'
);
const typeScriptPath = resolve(root, 'src/lib/generated/contracts.ts');
const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));

const rustScalars = {
  string: 'String',
  bool: 'bool',
  u8: 'u8',
  u16: 'u16',
  u32: 'u32',
  u64: 'u64',
  i64: 'i64',
  f64: 'f64'
};
const typeScriptScalars = {
  string: 'string',
  bool: 'boolean',
  u8: 'number',
  u16: 'number',
  u32: 'number',
  u64: 'number',
  i64: 'number',
  f64: 'number'
};

function parseType(type) {
  if (typeof type !== 'string' || type.length === 0)
    throw new Error(`invalid contract type ${String(type)}`);
  const optional = type.endsWith('?');
  const withoutOptional = optional ? type.slice(0, -1) : type;
  const array = withoutOptional.endsWith('[]');
  const base = array ? withoutOptional.slice(0, -2) : withoutOptional;
  return { optional, array, base };
}

function renderType(type, language) {
  const { optional, array, base } = parseType(type);
  const scalars = language === 'rust' ? rustScalars : typeScriptScalars;
  const named = scalars[base] ?? (schema.types[base] ? base : undefined);
  if (!named) throw new Error(`unsupported contract type ${type}`);
  let rendered = array
    ? language === 'rust'
      ? `Vec<${named}>`
      : `${named}[]`
    : named;
  if (optional)
    rendered =
      language === 'rust' ? `Option<${rendered}>` : `${rendered} | null`;
  return rendered;
}

function assertSchema() {
  if (schema.contract_version !== 1)
    throw new Error('contract version must be 1');
  for (const [command, definition] of Object.entries(schema.commands)) {
    if (typeof command !== 'string' || !schema.types[definition.response]) {
      throw new Error(`command ${command} references an unknown response type`);
    }
    if (definition.request !== null && !schema.types[definition.request]) {
      throw new Error(`command ${command} references an unknown request type`);
    }
  }
  for (const [typeName, fields] of Object.entries(schema.types)) {
    for (const [fieldName, fieldType] of Object.entries(fields)) {
      try {
        renderType(fieldType, 'rust');
        renderType(fieldType, 'typescript');
      } catch (error) {
        throw new Error(`${typeName}.${fieldName}: ${error.message}`);
      }
    }
  }
}

function rustSource() {
  const definitions = Object.entries(schema.types)
    .map(([typeName, fields]) => {
      const body = Object.entries(fields)
        .map(
          ([fieldName, fieldType]) =>
            `    pub ${fieldName}: ${renderType(fieldType, 'rust')},`
        )
        .join('\n');
      return `#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]\npub struct ${typeName} {\n${body}\n}`;
    })
    .join('\n\n');
  return `// Generated by scripts/contracts.mjs from contracts/querynot.v1.json. Do not edit.\nuse serde::{Deserialize, Serialize};\n\npub const CONTRACT_VERSION: u16 = ${schema.contract_version};\n\n${definitions}\n`;
}

function typeScriptSource() {
  const definitions = Object.entries(schema.types)
    .map(([typeName, fields]) => {
      const body = Object.entries(fields)
        .map(
          ([fieldName, fieldType]) =>
            `  ${fieldName}: ${renderType(fieldType, 'typescript')};`
        )
        .join('\n');
      return `export interface ${typeName} {\n${body}\n}`;
    })
    .join('\n\n');
  const commands = Object.entries(schema.commands)
    .map(([name, definition]) => {
      const request = definition.request ?? 'null';
      const singleLine = `  ${name}: { request: ${request}; response: ${definition.response} };`;
      if (singleLine.length <= 80) return singleLine;
      return `  ${name}: {\n    request: ${request};\n    response: ${definition.response};\n  };`;
    })
    .join('\n');
  return `// Generated by scripts/contracts.mjs from contracts/querynot.v1.json. Do not edit.\nexport const CONTRACT_VERSION = ${schema.contract_version} as const;\n\n${definitions}\n\nexport interface QueryNotCommands {\n${commands}\n}\n`;
}

assertSchema();
const outputs = [
  [rustPath, rustSource()],
  [typeScriptPath, typeScriptSource()]
];
const mode = process.argv[2];

if (mode === '--write') {
  for (const [path, source] of outputs) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, source, 'utf8');
  }
  process.stdout.write('generated Rust and TypeScript contract bindings\n');
} else if (mode === '--check') {
  for (const [path, source] of outputs) {
    if (readFileSync(path, 'utf8') !== source) {
      throw new Error(`${path} is stale; run npm run contracts:sync`);
    }
  }
  process.stdout.write('command/event bindings match contract version 1\n');
} else {
  throw new Error('usage: node scripts/contracts.mjs --write|--check');
}
