import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const schemaPath = resolve(root, 'contracts/querynot.v1.json');
const rustPath = resolve(
  root,
  'crates/querynot-core/src/generated/contracts.rs'
);
const typeScriptPath = resolve(root, 'src/lib/generated/contracts.ts');
const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));

const rustTypes = { string: 'String', u16: 'u16' };
const typeScriptTypes = { string: 'string', u16: 'number' };

function assertSchema() {
  if (schema.contract_version !== 1)
    throw new Error('contract version must be 1');
  for (const [command, definition] of Object.entries(schema.commands)) {
    if (typeof command !== 'string' || !schema.types[definition.response]) {
      throw new Error(`command ${command} references an unknown response type`);
    }
  }
  for (const [typeName, fields] of Object.entries(schema.types)) {
    for (const [fieldName, fieldType] of Object.entries(fields)) {
      if (!rustTypes[fieldType] || !typeScriptTypes[fieldType]) {
        throw new Error(
          `${typeName}.${fieldName} has unsupported type ${fieldType}`
        );
      }
    }
  }
}

function rustSource() {
  const definitions = Object.entries(schema.types)
    .map(([typeName, fields]) => {
      const body = Object.entries(fields)
        .map(
          ([fieldName, fieldType]) =>
            `    pub ${fieldName}: ${rustTypes[fieldType]},`
        )
        .join('\n');
      return `#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]\npub struct ${typeName} {\n${body}\n}`;
    })
    .join('\n\n');
  return `// Generated by scripts/contracts.mjs from contracts/querynot.v1.json. Do not edit.\nuse serde::{Deserialize, Serialize};\n\npub const CONTRACT_VERSION: u16 = ${schema.contract_version};\n\n${definitions}\n`;
}

function typeScriptSource() {
  const definitions = Object.entries(schema.types)
    .map(([typeName, fields]) => {
      const body = Object.entries(fields)
        .map(
          ([fieldName, fieldType]) =>
            `  ${fieldName}: ${typeScriptTypes[fieldType]};`
        )
        .join('\n');
      return `export interface ${typeName} {\n${body}\n}`;
    })
    .join('\n\n');
  const commands = Object.entries(schema.commands)
    .map(
      ([name, definition]) =>
        `  ${name}: { request: null; response: ${definition.response} };`
    )
    .join('\n');
  return `// Generated by scripts/contracts.mjs from contracts/querynot.v1.json. Do not edit.\nexport const CONTRACT_VERSION = ${schema.contract_version} as const;\n\n${definitions}\n\nexport interface QueryNotCommands {\n${commands}\n}\n`;
}

assertSchema();
const outputs = [
  [rustPath, rustSource()],
  [typeScriptPath, typeScriptSource()]
];
const mode = process.argv[2];

if (mode === '--write') {
  for (const [path, source] of outputs) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, source, 'utf8');
  }
  process.stdout.write('generated Rust and TypeScript contract bindings\n');
} else if (mode === '--check') {
  for (const [path, source] of outputs) {
    if (readFileSync(path, 'utf8') !== source) {
      throw new Error(`${path} is stale; run npm run contracts:sync`);
    }
  }
  process.stdout.write('command/event bindings match contract version 1\n');
} else {
  throw new Error('usage: node scripts/contracts.mjs --write|--check');
}
